kind: Service
apiVersion: v1
metadata:
  labels:
    app: metadata
  name: metadata-grpc-service
spec:
  selector:
    component: metadata-grpc-server
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    name: grpc-api
