name: Build and Deploy to GKE

on:
  push:
    branches: [ "test" ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: access_token
        access_token_lifetime: 900s
        create_credentials_file: true
        workload_identity_provider: 'projects/141066722035/locations/global/workloadIdentityPools/k8s-pool/providers/k8s-provider'
        service_account: 'kubeflow-oidc@burner-mayagarw-02.iam.gserviceaccount.com'


    # Set up kubectl
    - name: Set up Kubectl
      run: |-
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        curl -LO https://dl.k8s.io/release/v1.28.1/bin/linux/amd64/kubectl
        curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
        echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        gcloud components install gke-gcloud-auth-plugin
        # Set up kustomize

    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
          gcloud container clusters get-credentials cluster-1 --region us-central1 --project burner-mayagarw-02
          cd components/katib
          kubectl apply -k .

